### ISSUE TITLE
[BUG] Scale will go from 0 - 120

### ISSUE THREAD

**Issue by ChrisKatsaras** [y-takey/chartjs-plugin-stacked100#1]
Occasionally, the calculations made by this plugin will cause the final result to 100.1 instead of 100. This causes the chart to have another Y axis point. See example image below for reference. 
![image](https://user-images.githubusercontent.com/11506653/28031254-ac5fcf16-6574-11e7-9c7c-561da281b501.png)

As you can see, the third column is just slightly over 100 (adding up to 100.1) which creates this issue.

**Comment by ChrisKatsaras** [comment]
I think I found the issue causing this: 
![image](https://user-images.githubusercontent.com/11506653/28044893-036b75f2-65a8-11e7-96df-484295c38b3c.png)
Specifies that the **xAxis** ticks go from 0 - 100. If I'm correct, this means vertically stacked charts may run into some minor issues (just like it did).

**Quick fix?**
Simply change xAxis to be yAxis

**Long-term solution?**
Implement chartType option so that a user may differentiate between vertical and horizontal charts

**Comment by y-takey** [comment]
Hi @ChrisKatsaras, sorry for the delay. 

I had not consider about vertical bar chart. so, your advice is saved me, thank you very much! I just have fixed this issue, and published to npm registry.
could you update your plugin and test it?

**Comment by ChrisKatsaras** [comment]
Tested and looks good to me! Nice work, @y-takey  😄
