### ISSUE TITLE
Can't load script v1.5.1 on browser. "Uncaught ReferenceError: global is not defined"

### ISSUE THREAD

**Issue by cupsos** [y-takey/chartjs-plugin-stacked100#101]
### Bug reproduce

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
    <!--
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-stacked100@1.5.0"></script>
    -->
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-stacked100@1.5.1"></script>
</head>

<body>
</body>

</html>
```
![image](https://github.com/y-takey/chartjs-plugin-stacked100/assets/24942851/b60bed40-d2f4-4548-8075-e8f04ad0202c)

---

v1.5.0 works well but v1.5.1
I think this error is related to #87 and 49b3fd2db1430ae27ff97a0759063db5101d314a.

**Comment by y-takey** [comment]
Hi @cupsos ,
Thank you for your bug report. I appreciate your prompt notification. I have quickly addressed the issue by reverting the problematic commit and have released version 1.5.2. :)
