### ISSUE TITLE
Total percents are bigger then 100%

### ISSUE THREAD

**Issue by frenzymind** [y-takey/chartjs-plugin-stacked100#108]
My second bar has 7 * 14.3% what equal to 100.1% This makes grow Y axis to 120%
Raw data contains 7 values with 1. 

Is it possible to correct this behavior ? Thanks!

Percentage values:

![Screenshot from 2024-02-26 16-06-03](https://github.com/y-takey/chartjs-plugin-stacked100/assets/33678873/5a7cc058-3fdd-48ad-a95b-4cecc5fd8b45)

Raw values:

![Screenshot from 2024-02-26 16-54-06](https://github.com/y-takey/chartjs-plugin-stacked100/assets/33678873/ffefa879-bbfa-4130-8339-a99459709078)

**Comment by y-takey** [comment]
Hi @frenzymind , Thank you for the report :)
I'll try to fix it.

**Comment by y-takey** [comment]
I attempted to replicate this issue but was unable to do so. Here is my config:

```json
{
  "type": "bar",
  "data": {
    "labels": [""],
    "datasets": [
      { "label": "l1", "data": [1], "backgroundColor": "RGBA(255, 0, 0, 0.6)" },
      { "label": "l2", "data": [1], "backgroundColor": "RGBA(255, 165, 0, 0.6)" },
      { "label": "l3", "data": [1], "backgroundColor": "RGBA(255, 255, 0, 0.6)" },
      { "label": "l4", "data": [1], "backgroundColor": "RGBA(0, 128, 0, 0.6)" },
      { "label": "l5", "data": [1], "backgroundColor": "RGBA(0, 0, 255, 0.6)" },
      { "label": "l6", "data": [1], "backgroundColor": "RGBA(75, 0, 130, 0.6)" },
      { "label": "l7", "data": [1], "backgroundColor": "RGBA(128, 0, 128, 0.6)" }
    ]
  },
  "options": {
    "indexAxis": "x",
    "plugins": { "stacked100": { "enable": true } }
  }
}
```

And here is the displayed result:

<kbd>
<img width="636" alt="ss_issue108" src="https://github.com/y-takey/chartjs-plugin-stacked100/assets/1817802/5c28a99a-c859-4eee-b709-c9c5af58fadc">
</kbd>


By the way, in the plugin, the `scale` option is set to `{ max: 100 }`. If you have already specified something, it won't override it. 
If you have made any prior specifications, try adding `{ max: 100 }` and see if it resolves the issue.

**Comment by frenzymind** [comment]
> If you have made any prior specifications, try adding { max: 100 } and see if it resolves the issue.

That's work perfect! Just a little typo: not `scale` , but `scales`
I don't define this parameter in any of options, but explicitly setting to 100 works!
Thanks for your time! 
```ts
export const stackedPercentOptions: ChartOptions<'bar'> = {
  scales: {
    x: {
      stacked: true,
    },
    y: {
      stacked: true,
      ticks: {
        callback: function (value, index, ticks) {
          return value + '%';
        },
      },
      max: 100,
    },
  },
  plugins: {
    stacked100: {
      enable: true,
    },
    tooltip: {
      callbacks: {
        label: tooltipItem => {
          const data = tooltipItem.chart.data;
          const datasetIndex = tooltipItem.datasetIndex;
          const index = tooltipItem.dataIndex;
          const datasetLabel = data.datasets[datasetIndex].label || '';

          const originalValue = data.originalData![datasetIndex][index];
          const rateValue = data.calculatedData![datasetIndex][index];

          return `${datasetLabel}: ${rateValue}% (${originalValue})`;
        },
      },
    },
  },
};
```
