### ISSUE TITLE
Request: minified version for using jsDelivr with SRI

### ISSUE THREAD

**Issue by liamie** [y-takey/chartjs-plugin-stacked100#116]
I use this library and use jsDelivr to install it. It works great.  However I would also like to use Subresource Integrity (SRI) so could you include a static version of .min.js file so jsDelivr does not generate the .min.js on the fly.

Thank you.

**Comment by y-takey** [comment]
Hi @liamie , Thank you for your request!

I'll consider providing the .min.js file. However, I'm not very familiar with it, so it might take some time. Please don't expect too much.
If possible, I'd welcome a pull request if you could provide one.

**Comment by y-takey** [comment]
Hi @liamie , The index.js file we currently provide is already minified. Therefore, would specifying this file directly satisfy your request? For example, for version 1.5.3, it would look like this:

```html
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-stacked100@1.5.3/build/index.js" integrity="sha384-+ZcBbusoy89M1vBXUK03MLh/hfpnw2kdqV6epVv2Baa7lRyTNDoERrESR+pw3G6A" crossorigin="anonymous"></script>
```

**Comment by liamie** [comment]
Hi @y-takey,  it was an earlier version being used which was not minified. So yes, I think this will work. Thank you.

**Comment by y-takey** [comment]
Thank you for your prompt response. I’m glad to hear that it seems to be working well. Please let me know if you encounter any further issues.
