### ISSUE TITLE
Deselect All Data From Legend

### ISSUE THREAD

**Issue by smcguinness** [y-takey/chartjs-plugin-stacked100#12]
Replicated At [Case.1 basic pattern](https://y-takey.github.io/chartjs-plugin-stacked100/)

Issue: By clicking to hide all datapoints using the legend, the chart is unable to re-render correctly when clicking on legend to show data. Singular hiding and showing does not seem to have an issue.

**Comment by y-takey** [comment]
Hi @smcguinness ,

Thanks for your report!
This issue seems to occur when repeatedly and quickly click on legend. It isn't occurs after wait a bit(e.g. one sec).
I've fixed this issue and published a newer version :) Could you retry it?

**Comment by smcguinness** [comment]
Yup...this fixed the issue in my project and I also tested it on examples too. Thanks!

**Comment by y-takey** [comment]
Thanks for the quick response!
