### ISSUE TITLE
How to display the original value and not the computed value?

### ISSUE THREAD

**Issue by Li9x1** [y-takey/chartjs-plugin-stacked100#14]
Thanks a ton for the plugin! It works like a charm. I would like to display the original value instead of the rateValue%. Please note, I am using the [chartjs-plugin-datalabels](https://chartjs-plugin-datalabels.netlify.com/) to display the data. Without chartjs-plugin-stacked100 it displays the original value, once i include it for 100% stacked chart, the display label changes to rate percentage. What change should i make?

![stackchart](https://user-images.githubusercontent.com/10879031/34768938-44b018c8-f622-11e7-8637-5bfccec41bcb.PNG)

**Comment by y-takey** [comment]
Hi @Li9x1 ,
Thanks for your question :)
This plugin set original values in `chart.data.originalData`, so you can use formatter option of datalabels plugin like following:

```js
new Chart(document.getElementById("my-chart-1"), {
  type: "bar",
  data: {...},
  options: {
    plugins: {
      datalabels: {
        formatter: (_value, context) => context.chart.data.originalData[context.datasetIndex][context.dataIndex]
      },
      stacked100: { enable: true }
    }
  }
});
```

**Comment by Li9x1** [comment]
Wow! Thanks much @y-takey !!! that works! :)
