### ISSUE TITLE
How to show raw data in tooltip legend

### ISSUE THREAD

**Issue by dlewand691** [y-takey/chartjs-plugin-stacked100#17]
I'd like to show the raw tooltip legend percentage only and not the computed valued. I was able to do it for the bar label but can't seem to get it to work for the tooltip. What would be the proper way?

<img width="503" alt="screen shot" src="https://user-images.githubusercontent.com/1159913/40315903-b58225bc-5cea-11e8-8952-5d47f45919d1.png">

**Comment by y-takey** [comment]
Hi @dlewand691 :) thanks for the issue.

You can show raw data with tooltip option. like this:

```javascript
new Chart(~, {
  ~,
  options: {
    tooltips: {
      callbacks: {
        label: (tooltipItem, data) => {
          const datasetIndex = tooltipItem.datasetIndex;
          const datasetLabel = data.datasets[datasetIndex].label;
          const originalValue = data.originalData[datasetIndex][tooltipItem.index];
          return `${datasetLabel}: ${originalValue}`;
        }
      }
    },
    plugins: {
      stacked100: { enable: true, replaceTooltipLabel: false }
    }
  }
});
```

**Comment by dlewand691** [comment]
Thanks for the super quick reply! It wasn't working and realized I needed to update. All is perfect now, thank you!

**Comment by y-takey** [comment]
I'm glad to help you!
