### ISSUE TITLE
Percentages overwritten by chartjs-plugin-datalabels

### ISSUE THREAD

**Issue by glenn-barnett** [y-takey/chartjs-plugin-stacked100#21]
Not sure whether to log this here or at https://github.com/chartjs/chartjs-plugin-datalabels, so I'll do both.

chartjs-plugin-datalabels adds numerical labels atop the chart shapes.

When combined with chartjs-plugin-stacked100, it creates a problem on hover - the datalabels are re-set, changed from the percentage-of-stack value back to the raw values.

Example jsfiddle: https://jsfiddle.net/y9j0ngrd/

**Comment by y-takey** [comment]
Hi @glenn-barnett , thanks for your issue :)
Please add `formatter` option to chartjs-plugin-datalabels, when combine the both plugins.
like this https://jsfiddle.net/vywosndr/1/

**Comment by glenn-barnett** [comment]
That was it - thanks!
