### ISSUE TITLE
Negative values are not handled correctly

### ISSUE THREAD

**Issue by liezlsantos** [y-takey/chartjs-plugin-stacked100#31]
When you have negative values in the dataset, the percentage is computed without using the absolute value of the data:

IMO, this wrong and the values are not represented correctly:
![before-stacked-100-min0](https://user-images.githubusercontent.com/6415921/56037031-f464c880-5d60-11e9-9c96-9b5581914730.png)

After adjusting min and max of the x-axis to -100 and 200, respectively (so we can see all the bars):
![before-stacked-100](https://user-images.githubusercontent.com/6415921/56037054-05add500-5d61-11e9-8fd0-a5762ab6d1c6.png)

**Suggestion**:
Compute the percentage using absolute value of the data (for reference this is also how it is done in MS Excel):
![after-stacked-100](https://user-images.githubusercontent.com/6415921/56037134-33931980-5d61-11e9-8ff9-829aaeeca286.png)

I submitted a [pull request](https://github.com/y-takey/chartjs-plugin-stacked100/pull/30/commits/3631624be4c266a475deb02e8acf79a41ca6bf2b).

**Comment by y-takey** [comment]
Hi @liezlsantos , sorry for the delay.
Thanks for your issue and nice suggestion. :) I agree your idea completely. so, merged PR #30 and published a newer npm module(v0.7.1).

thank you very much!

**Comment by liezlsantos** [comment]
Awesome! Thanks, @y-takey.
