### ISSUE TITLE
Wrong initial values

### ISSUE THREAD

**Issue by felipeands** [y-takey/chartjs-plugin-stacked100#34]
When I load data into stacked100 with ChartDataLabels, the initial data displayed area wrong.
The right numbers appears after I move mouse hover the component.

**Comment by y-takey** [comment]
Hi @felipeands , Thank you for the issue. :)
Could you provide example code to reproduce the issue?

**Comment by Extnow** [comment]
If someone else has faced this problem, you should take the values from the originalData array that this plugin creates

It helped me
