### ISSUE TITLE
Vue-Chartjs Example

### ISSUE THREAD

**Issue by quiquegarcia** [y-takey/chartjs-plugin-stacked100#35]
Hello,

I'm trying to use this plugin in a Vue component via [Vue-Chartjs](https://vue-chartjs.org/)

Can you provide an example how to use it with Vue or provide a component on your script to easily import your plugin?

**Comment by y-takey** [comment]
Hi @quiquegarcia ,

I created an example on codepen. :)

https://codepen.io/y-takey/pen/XWmQoYg

---
If you use npm and babel, maybe need the follow code.

```js
import Chart from 'chart.js';
window.Chart = Chart
import 'chartjs-plugin-stacked100';
import VueChartJs from 'vue-chartjs'
```
