### ISSUE TITLE
Is it possible to change the bar values?

### ISSUE THREAD

**Issue by marcelod** [y-takey/chartjs-plugin-stacked100#36]
It is shown every 10, but I would like to be able to configure and add the percent sign.

The first image is how I would like to leave it and the second is how it looks. They have different data, but just exemplify the markings in the bar

![Captura de tela de 2020-06-05 22-24-08](https://user-images.githubusercontent.com/441936/83932992-50678900-a77b-11ea-80e9-91022c3e34de.png)
![Captura de tela de 2020-06-05 22-22-43](https://user-images.githubusercontent.com/441936/83932994-51001f80-a77b-11ea-9220-37cd8ef7a8d2.png)

**Comment by marcelod** [comment]
It is shown every 10, but I would like to be able to configure and add the percent sign.

The first image is how I would like to leave it and the second is how it looks. They have different data, but just exemplify the markings in the bar

**Comment by y-takey** [comment]
Hi @marcelod :)

You can use the `ticks` option. (it is general option of chart.js)
like this:

```js
new Chart(document.getElementById("my-chart"), {
  type: "horizontalBar",
  data: {},
  options: {
    scales: {
      xAxes: [{ ticks: { stepSize: 25, callback: (val) => `${val}%` } }], # **here**
    },
    plugins: {
      stacked100: { enable: true },
    },
  },
});

```

**Comment by marcelod** [comment]
Hi @y-takey , thanks a lot for the help and the plugin is very good
