### ISSUE TITLE
Create a tag please?

### ISSUE THREAD

**Issue by damienderoistecso** [y-takey/chartjs-plugin-stacked100#37]
I use this library in my project and use jsDelivr to install it. It works great but I don't like having to refer to the master branch as the source as this may be modified over time and I don't want to risk anything breaking at my end.

Could you create a tag of the master branch so I can point to a this instead please. I would really appreciate it. Thanks.

**Comment by y-takey** [comment]
Hi @damienderoistecso , thanks for your pointing :)
I forgot to push the tag, so pushed all tags. Thanks.

**Comment by damienderoistecso** [comment]
@y-takey Thanks you so much!
