### ISSUE TITLE
Values shown while hovering are changing back to percentage values

### ISSUE THREAD

**Issue by manikandan-velu** [y-takey/chartjs-plugin-stacked100#4]
Initially while hovering over the bars the values shown are the data that I specified in the data set. But once I click on any legend(This will make that portion to disappear) and hover over any bars the values shown are percentage values. Please fix this bug

**Comment by y-takey** [comment]
Hi @manikandan-velu ,

Thanks for the report. I've fixed this bug, and updated npm module to v0.2.1. Please test after update your plugin.

best regards,

**Comment by manikandan-velu** [comment]
Hey @y-takey , Thanks for this quick fix 🥇 . Working fine for me  👍
