### ISSUE TITLE
Chart.js 3.0 support

### ISSUE THREAD

**Issue by benmccann** [y-takey/chartjs-plugin-stacked100#44]
Chart.js 3.0 is out now. It'd be great to see this plugin updated

**Comment by y-takey** [comment]
Hi @benmccann , Thank you for telling me about chart.js@3 🎉 
I would like to update this plugin in the near future!

**Comment by jagdaleganesh** [comment]
Hi , I would like to use this plugin. How I can use with latest ChartJS version. I need to register the plugin first before use. 
Please let me know how I can use the it with latest chartjs version.
In case this plugin is not yet updated, is there any workaround to use with latest chartjs version. 

@y-takey , I am waiting for your reply. 

Thanks,

**Comment by y-takey** [comment]
Hi @jagdaleganesh , thanks for the request :)
It is WIP now, so please wait a little more.

**Comment by y-takey** [comment]
published chartjs-plugin-stacked100@1.0.0 supported Chart.js@3 :)

**Comment by jagdaleganesh** [comment]
Thank you

**Comment by mkismy** [comment]
Using the [example on readme](https://github.com/y-takey/chartjs-plugin-stacked100#examples) via CDN, it does not work as expected and become a normal bar chart.

```html
<div style="width: 700px; height: 300px">
  <canvas id="my-chart"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-stacked100"></script>
<script type="text/javascript">
Chart.register(ChartjsPluginStacked100);

new Chart(document.getElementById("my-chart"), {
  type: "bar",
  data: {
    labels: ["Foo", "Bar"],
    datasets: [
      { label: "bad", data: [5, 25], backgroundColor: "rgba(244, 143, 177, 0.6)" },
      { label: "better", data: [15, 10], backgroundColor: "rgba(255, 235, 59, 0.6)" },
      { label: "good", data: [10, 8], backgroundColor: "rgba(100, 181, 246, 0.6)" }
    ]
  },
  options: {
    indexAxis: "y",
    plugins: {
      stacked100: { enable: true }
    }
  }
});
</script>
```

![image](https://user-images.githubusercontent.com/8445575/133106035-54005ec6-09be-4089-bc46-100376a75730.png)


When adding stacked option, the bar stacks but doesn't become a 100% stacked bar.
```javascript
  options: {
    indexAxis: "y",
    scales: {
      x: { stacked: true },
      y: { stacked: true },
    },
    plugins: {
      stacked100: { enable: true }
    }
  }
```

![image](https://user-images.githubusercontent.com/8445575/133106740-200adb78-d185-475b-ba47-85fe3bd68b80.png)


@y-takey Can you check if there are anything wrong with the code above?

**Comment by y-takey** [comment]
@mkismy Thanks for the issue :)
Sorry, the example was wrong. here is correctly example.

```js
Chart.register(ChartjsPluginStacked100.default);  // HERE!

new Chart(document.getElementById("my-chart"), {
  type: "bar",
  data: {
    labels: ["Foo", "Bar"],
    datasets: [
      { label: "bad", data: [5, 25], backgroundColor: "rgba(244, 143, 177, 0.6)" },
      { label: "better", data: [15, 10], backgroundColor: "rgba(255, 235, 59, 0.6)" },
      { label: "good", data: [10, 8], backgroundColor: "rgba(100, 181, 246, 0.6)" }
    ]
  },
  options: {
    indexAxis: "y",
    plugins: {
      stacked100: { enable: true }
    }
  }
});
```

I will fix readme later.

**Comment by mkismy** [comment]
Thank you 😁
