### ISSUE TITLE
Could not find a declaration file for module 'chartjs-plugin-stacked100'

### ISSUE THREAD

**Issue by ucorpintegration** [y-takey/chartjs-plugin-stacked100#46]
I am trying to use `chartjs-plugin-stacked100` in a React App:

    import React, { useEffect, useState } from 'react';
    import { Chart } from 'react-chartjs-2';
    import ChartjsPluginStacked100 from 'chartjs-plugin-stacked100';
    
    const ConnectedTime = () => {
      // https://designcode.io/react-hooks-handbook-usestate-hook
      // https://designcode.io/react-hooks-handbook-fetch-data-from-an-api
      useEffect(() => {   }, []);
      return <>
          {
    	<div>
    	    <ChartjsPluginStacked100
    	      type="bar"
    	      data={{
        		labels: ["Foo", "Bar"],
        		datasets: [
        		  { label: "bad", data: [5, 25], backgroundColor: "rgba(244, 143, 177, 0.6)" },
        		  { label: "better", data: [15, 10], backgroundColor: "rgba(255, 235, 59, 0.6)},
	        	  { label: "good", data: [10, 8], backgroundColor: "rgba(100, 181, 246, 0.6)" }]	
	          }}
    	      options={{ 
        		indexAxis: "y",
    	    	plugins: {
    		      stacked100: { enable: true }
    		    }
    	      }} />
    	</div>
          }
      </>
    }
    
    export default ConnectedTime

When I `yarn start` this piece of code, I get the error: 

    TypeScript error in /home/mihamina/.../src/Components/ConnectedTime/ConnectedTime.tsx(4,37):
    Could not find a declaration file for module 'chartjs-plugin-stacked100'. 
    '/home/mihamina/.../node_modules/chartjs-plugin-stacked100/build/index.js' implicitly has an 'any' type.
    Try `npm i --save-dev @types/chartjs-plugin-stacked100` if it exists 
    or add a new declaration (.d.ts) file containing 
    `declare module 'chartjs-plugin-stacked100';`

Issuing `npm i --save-dev @types/chartjs-plugin-stacked100` : The package does not exist.

I dont quite understand about the `.d.ts` file:

 - Do I create it at the root of the project? (same folder as `package.json`?)
 - Is the required name really `.d.ts` or should I prepend the name with `chartjs-plugin-stacked100`?

**Comment by y-takey** [comment]
No, maybe you don't need the `.d.ts` file.
Can you try like below code?

```js
import React, { useEffect, useState } from 'react';
import { Chart } from 'react-chartjs-2';
import ChartjsPluginStacked100 from "chartjs-plugin-stacked100";

Chart.register(ChartjsPluginStacked100); // ★add this line

const ConnectedTime = () => {
  return <>
      {
	<div>
	    <Chart // ★change component name
	      type="bar"
	      data={{}}
	      options={{}} />
	</div>
      }
  </>
}
```

**Comment by ucorpintegration** [comment]
Hello @y-takey , 

This is now the code:

    import React, { useEffect, useState } from 'react';
    import { Chart } from 'react-chartjs-2';
    import ChartjsPluginStacked100 from 'chartjs-plugin-stacked100';
    Chart.register(ChartjsPluginStacked100); //
    
    const ConnectedTime = () => {
      // https://designcode.io/react-hooks-handbook-usestate-hook
      // https://designcode.io/react-hooks-handbook-fetch-data-from-an-api
      useEffect(() => {   }, []);
      return <>
          {
            <div>
                <Chart                // IDE Warning at this line
                  type="bar"
                  data={{
                    labels: ["Foo", "Bar"],
                    datasets: [
                      { label: "bad", data: [5, 25], backgroundColor: "rgba(244, 143, 177, 0.6)" },
                      { label: "better", data: [15, 10], backgroundColor: "rgba(255, 235, 59, 0.6)" },
                      { label: "good", data: [10, 8], backgroundColor: "rgba(100, 181, 246, 0.6)" }]        
                  }}
                  options={{ 
                    indexAxis: "y",
                    plugins: {
                      stacked100: { enable: true }
                    }
                  }} />
            </div>
          }
      </>
    }
    export default ConnectedTime
    
I still get:

    Could not find a declaration file for module 'chartjs-plugin-stacked100'. '/home/mihamina/.../node_modules/chartjs-plugin-stacked100/build/index.js' implicitly has an 'any' type.

Plus, my IDE warns me about "Chart" could not be used as a JSX component.

**Comment by y-takey** [comment]
Hello @ucorpintegration  , thanks for the reply :)

Do you use typescript?

**Comment by ucorpintegration** [comment]
@y-takey , Yes I do. Is this the reason of the failure?

**Comment by y-takey** [comment]
No, maybe i failured compile the plugin.
Could you try below code?

```jsx
import React, { useEffect, useState } from 'react';
import { Bar } from 'react-chartjs-2';
import ChartjsPluginStacked100 from 'chartjs-plugin-stacked100';

const ConnectedTime = () => {
  // https://designcode.io/react-hooks-handbook-usestate-hook
  // https://designcode.io/react-hooks-handbook-fetch-data-from-an-api
  useEffect(() => {   }, []);
  return <>
      {
        <div>
            <Bar   // CHANGE
              type="bar"
              data={{
                labels: ["Foo", "Bar"],
                datasets: [
                  { label: "bad", data: [5, 25], backgroundColor: "rgba(244, 143, 177, 0.6)" },
                  { label: "better", data: [15, 10], backgroundColor: "rgba(255, 235, 59, 0.6)" },
                  { label: "good", data: [10, 8], backgroundColor: "rgba(100, 181, 246, 0.6)" }]        
              }}
              plugins={[ChartjsPluginStacked100]}  // ADD
              options={{ 
                indexAxis: "y",
                plugins: {
                  stacked100: { enable: true }
                }
              }} />
        </div>
      }
  </>
}
```

**Comment by rakotomandimby** [comment]
Hello @y-takey , here is a PR in order to make it work ;-)

**Comment by y-takey** [comment]
Hello @rakotomandimby , thanks your PR :) 
merged the PR for now.

**Comment by y-takey** [comment]
I published declaration files for typescript in version 1.0.4, so you don't need your declaration file now.
