### ISSUE TITLE
stacked100 init

### ISSUE THREAD

**Issue by soloraid** [y-takey/chartjs-plugin-stacked100#47]
after init stacked100, when I filtered a legend then max height changed but after reload fixed 100% even filtering

**Comment by soloraid** [comment]
![Untitled](https://user-images.githubusercontent.com/46398811/132328531-1193ab15-e0a7-47c8-a0dc-77f7d50d9705.png)

**Comment by y-takey** [comment]
Hi @soloraid , thanks for the issue :)
I fixed this and published the plugin v1.0.1, could you try after update your plugin?

**Comment by soloraid** [comment]
yeah , thanks , now filter legend all 100% 
very fast you fixed it!

**Comment by y-takey** [comment]
Thanks :)
