### ISSUE TITLE
Min value is not well calculated

### ISSUE THREAD

**Issue by TheTisiboth** [y-takey/chartjs-plugin-stacked100#52]
Hello everyone, and first of all, thanks for the work, this plugin is really useful.

I am using it in a React project, and I managed to make it work with typescript as well (it took me some days haha)
But now, I observe that the minimum value of my X axis is "wrong:
<img width="1414" alt="Screenshot 2021-11-29 092349" src="https://user-images.githubusercontent.com/37371049/143833793-de5a5989-db8b-4270-92c1-510729c8c5ba.png">

Actually, it's not totally wrong, because this min value is the overall min value for the whole datasets. I can verify this by hiding the dataset `packaging`:
<img width="1406" alt="Screenshot 2021-11-29 092418" src="https://user-images.githubusercontent.com/37371049/143833932-5347bb40-bac4-402e-b79a-9dcdadc61e81.png">

So is there a way to recompute the min value, everytime we show/hide a dataset, not to display the overall min, but to have the min according to the showed dataset? So in my example, the effective min in the first example should be -20%, and if I hide the dataset `packaging`, it should be recomputed, to be -100%
It would avoid to have the chart shown on just half of the screen, like on the first screenshot

Thanks for your help!

EDIT:
I can see that this -100% is actually maybe not linked to the values itself, but simply because I have negative values, as this comments suggests: https://github.com/y-takey/chartjs-plugin-stacked100/pull/30
But anyway, I'm still interested for some hints about this !

EDIT 2: I also observed that if I update my code, by just adding a blank line (for instance), then save, It will update my react website, and then it will have the wanted behavior (with dynamic min value computed each time a dataset is hidden/shown).
So it is not a fix, but I imagine that having the wanted behavior by default should be easy 

Here is a [reproducible example](https://codesandbox.io/s/dreamy-wozniak-z4tlg?file=/src/App.tsx) (it's maybe a bit messy since this is under development, but If you need me to comment something, let me know)

**Comment by TheTisiboth** [comment]
I found a workaround, but it is rather temporary I would say, since it is not elegant at all.
Anyway, as I said, I get the expected behavior if my react component is refreshed (whenever I update the source code).
So I thought that I could programmatically achieve this, and I found this snippet on the web, which is doing it:
```
const [, updateState] = useState();
const forceUpdate = useCallback(() => updateState({}), []);
```
Then, I created a simple plugin that is forcing the update of my component once, in the beginning, and that does the trick:
```
const updatePlugin: Plugin<"bar"> = {
        id: "updatePlugin",
        beforeInit: () => {
            // It will update my component once, just before the chart is initialized
            forceUpdate()
        }
    }
```

So this is maybe just a React related issue, I'm not sure

**Comment by y-takey** [comment]
Hi @TheTisiboth , thanks for the issue and a reproducible example :)
I will look into it.

**Comment by y-takey** [comment]
This is expected behavior, but the negative scale made variable.
You can use `fixNegativeScale` option, after update this plugin to v1.1.0.

```tsx
<Bar data={data} options={{ plugins: { stacked100: { enable: true, fixNegativeScale: false } } }} />
```

Thanks for your pointing :)

**Comment by TheTisiboth** [comment]
Oh great, that is exactly was I was expecting, thank you a lot for your quick fix, that was really fast!!!
