### ISSUE TITLE
Scale highest bar to 100%

### ISSUE THREAD

**Issue by TheTisiboth** [y-takey/chartjs-plugin-stacked100#53]
I have an idea about a new feature (or if it is already existing, I would be really interested!)
![Image Pasted at 2021-11-29 16-15](https://user-images.githubusercontent.com/37371049/143895727-db2f3069-2729-4942-a145-8fc295209a0e.png)

Beeing able to scale the highest bar to 100%, and the rest would be proportional to the highest bar of a stack. Does it make sense that I post this here, or should I post it elsewhere ?

**Comment by y-takey** [comment]
Thanks for your new feature idea :)
Did you mean you want to use only calculated (percentage) values?
If so, you can use `stacked` option. like this:

```tsx
const options = {
  scales: { x: { stacked: false }, y: { stacked: false } },
  plugins: { stacked100: { enable: true } }
}

<Bar data={data} options={options} />
```

**Comment by TheTisiboth** [comment]
Ideally, I would like to use both values, original and percentage value, like it is already done with your plugin

**Comment by TheTisiboth** [comment]
That is why I think your plugin would be useful to achieve this. What do you think about this ?

**Comment by y-takey** [comment]
Sorry for the delay.
I was misunderstanding your idea, but i think now probably that i understand correctly your idea.
I agree your idea is interesting! i will try to implement it.

Thanks!

**Comment by y-takey** [comment]
I implement it experimentally, and deploy a demo page.(not publish a new version npm yet)
Could you check if it matches your image?
https://y-takey.github.io/chartjs-plugin-stacked100/#my-chart-10

**Comment by TheTisiboth** [comment]
Thank you @y-takey ! This is exactly what I was thinking about! That's great :)

**Comment by y-takey** [comment]
Thank you for quick response :)
I publish chartjs-plugin-stacked100@v1.2.0, you can use `individual` option after upgrade the plugin.

**Comment by TheTisiboth** [comment]
Thanks for the quick implementation =D
Ok great, that sounds good!
