### ISSUE TITLE
initial dataset.hidden=true doesn't scale visible bars to 100%

### ISSUE THREAD

**Issue by glenn-barnett** [y-takey/chartjs-plugin-stacked100#58]
If a dataset is initially hidden, the other datasets are not scaled up to 100%:
![image](https://user-images.githubusercontent.com/9353689/146998939-0bb27a80-3166-4960-a467-fd32163f34a7.png)

whereas if the dataset is initially visible and then the legend clicked to hide it, the other datasets are properly scaled up to 100%:
![image](https://user-images.githubusercontent.com/9353689/146998992-331bf762-f80d-40e4-ac84-acc93df8c92d.png)

repro case: https://codepen.io/_gb/pen/qBPXMLm

thanks for all the work you do in maintaining this plugin!

**Comment by y-takey** [comment]
Hi @glenn-barnett , thanks for the issue :)
I fixed it and published the plugin@v1.1.5.
Thanks!
