### ISSUE TITLE
[Feature] Stacked group bar + group scale

### ISSUE THREAD

**Issue by TheTisiboth** [y-takey/chartjs-plugin-stacked100#59]
I was thinking about a new feature: it would mix stacked bar and group bar, as well as the individual feature that was already implemented in you plugin (in the version [1.2.0](https://github.com/y-takey/chartjs-plugin-stacked100/releases/tag/v1.2.0)).
So in the end, we would have  stack bars (each bar contains a set of data), and they are grouped. But in each group, the biggest bar is scaled to 100% (as it is already the case with the individual option, but it is relative to each group, not globally).

Do you think that it would be easy to implement? does it makes sense to you ? For my personal interest it would be really helpful, but I'm sure some other people may be interested =D

Here is a draft of this feature:
![WhatsApp Image 2022-01-10 at 11 41 22](https://user-images.githubusercontent.com/37371049/148752869-e4e854fe-8e81-4d9a-9b76-c70c2a47d7e3.jpeg)

**Comment by y-takey** [comment]
I agree with your thoughts. However, the implementation is not easy and it will take time. :(

**Comment by TheTisiboth** [comment]
Yes, it is what I thought. Well anyway, it is just a proposal =D

**Comment by y-takey** [comment]
Thanks for your proposal. I'll look into implementing it.

**Comment by TheTisiboth** [comment]
Ok great, amazing :)

**Comment by TheTisiboth** [comment]
Hello @y-takey ! Actually, I was thinking that maybe I could help you with developing this feature, since it would really be interesting for me, and maybe you don't have the time to do it yourself (I would understand). But then I would need to have some explanations about the code since I don't really know how it works under the hood. Would you have the time to explain to me a bit how everything works, so I could try to contribute? Thank you!

**Comment by y-takey** [comment]
Hello @TheTisiboth :) Of course! Thanks for your contribution.
But, there may be some explanations that are difficult to understand in my poor English. so feel free to ask any questions you have.

What this plugin does is very simple. The general flow is as follows.

1. calcuate denominator from input datasets. (func [summarizeValues](https://github.com/y-takey/chartjs-plugin-stacked100/blob/master/src/plugin.ts#L8) )
2. replace datasets with the value obtained by dividing the original value by the denominator.

I added [a unit test](https://github.com/y-takey/chartjs-plugin-stacked100/blob/master/src/test/plugin.test.ts#L43) for this case. You probably need to change only func `summarizeValues`.

**Comment by y-takey** [comment]
I've implemented this feature and released v1.2.1.
Feel free to reopen this issue if you notice anything.

**Comment by TheTisiboth** [comment]
Oh great thank you, it is perfect :)
