### ISSUE TITLE
Percentage calculation failed using stack option

### ISSUE THREAD

**Issue by datenwort** [y-takey/chartjs-plugin-stacked100#6]
Hi,

very nice library. I have a use case where I want to show a grouped set of stacked bars. The system did not differ between the stacks, so that all items over all stackgroups will be used to calculation the 100%.

BR

Short example

```
labels: ["C1", "C2"],
    datasets: [
        { label: "L1", stack: 'Stack 0', data: [3, 2] },
        { label: "L2", stack: 'Stack 0', data: [1, 1] },
        { label: "L1", stack: 'Stack 1', data: [0, 3] },
        { label: "L2", stack: 'Stack 1', data: [1, 4] }
]
```

**Comment by y-takey** [comment]
Hi @datenwort ,

Thanks for your report. :) I've fixed this bug, and updated npm module to v0.3.0. 
Could you test after update your plugin when you have time?

**Comment by datenwort** [comment]
That's service. Works like a charm.

**Comment by y-takey** [comment]
Thanks! :)

**Comment by datenwort** [comment]
Hi,

found a small side effect. Now you need definitely a stack option in your dataset. So either this should be mentioned or maybe there is a way to avoid it for simple graphs.

**Comment by y-takey** [comment]
Hi, 

could you tell me the detail? (sorry my english is  poor)
Did you mean that it don't works if there is no `stack` option in the dataset? 

e.g. `{ datasets: [{ data: [10] }, ...] }` don't works, so, should be `{ datasets: [{ data: [10], stack: 'some' }, ...] }` ?

thanks,

**Comment by datenwort** [comment]
Hi,

correct understanding. If you leave out the stack option, the chart will not be drawn.

**Comment by y-takey** [comment]
Thank you, 

Hmm, I've tested datasets that there is no stack option, then it works fine. 
https://github.com/y-takey/chartjs-plugin-stacked100/blob/master/test/index.js#L5
(open https://github.com/y-takey/chartjs-plugin-stacked100/blob/master/test/index.html to see the result)

I can't reproduce this issue. could you show me your source code?

**Comment by datenwort** [comment]
Seems to be an issue on myside. After changing it, I cannot reproduce it. So everything works fine.
