### ISSUE TITLE
stacked100 not working with undefined datasets

### ISSUE THREAD

**Issue by soloraid** [y-takey/chartjs-plugin-stacked100#62]
Stacked100:
![stacked100](https://user-images.githubusercontent.com/46398811/150632397-7d2a165e-ba4d-4319-97de-5b640df77459.PNG)

stacked:
![stacked](https://user-images.githubusercontent.com/46398811/150632402-9354dbae-c0b2-4df5-9940-07d16e7d870a.PNG)

in stacked100Chart'descriptor "south Dakota"  one of legends undefined, so the stacked100 didn't show anything but in stacked chart with same data is fine.
Thanks for your attention. I'm looking forward to your reply.

**Comment by y-takey** [comment]
Hi @soloraid , thanks for the issue :)
Could you provide your dataset?

**Comment by soloraid** [comment]
[dataset.txt](https://github.com/y-takey/chartjs-plugin-stacked100/files/7920268/dataset.txt)
this is dataset

**Comment by y-takey** [comment]
@soloraid thanks for the dataset.
This problem was not reproduced in v1.2.0. 
Which version of the plugin are you using?

**Comment by soloraid** [comment]
thanks for your replay.
my version 1.0.1.
update to your version and fixed.
