### ISSUE TITLE
Tooltip not show with percentage as per example

### ISSUE THREAD

**Issue by hisuwh** [y-takey/chartjs-plugin-stacked100#79]
The chart just shows the percentage value without the `%` symbol and without the underlying value.

![image](https://user-images.githubusercontent.com/4470351/180180772-becee079-9b39-4ca7-9027-3fb4e50def26.png)

Trying to reproduce this in a code pen but cannot seem to - not sure if this is something to do with me using Vue

(Also side note I can only get it to work if I set `stacked: true` on the axis - this is not specified in the example)

**Comment by y-takey** [comment]
Hi @hisuwh , Thank you for the issue.

You can use `tooltips` option to show the percentage value with the `%` symbol. please read the [README](https://github.com/y-takey/chartjs-plugin-stacked100#use-your-tooltip-label) for details.

Does this way solve your problem?

**Comment by hisuwh** [comment]
@y-takey yh I have set up the tooltip callback to do this manually - this actually works better for me because I want to show the total with the value, e.g. `33% (2 / 6)`

Thanks
