### ISSUE TITLE
Compatability issues with IE

### ISSUE THREAD

**Issue by ManikandanThangavelu** [y-takey/chartjs-plugin-stacked100#9]
The plugin is having issues with IE(Internet Explorer). I'm facing this issue with IE - "Object doesn't support property or method 'from'".

**Comment by y-takey** [comment]
Hi @ManikandanThangavelu ,

Thanks for your reporting, and sorry for the delay.
I've fixed this issue, and published the newer version(0.4.2). Could you try it after update your plugin?

**Comment by ManikandanThangavelu** [comment]
It has been fixed, Thank you :)
